version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"

  market:
    build:
      context: ./market
    depends_on:
      - postgres_market

  giver:
    build:
      context: ./giver
    depends_on:
      - postgres_giver

  postgres_market:
    image: postgres:latest
    environment:
      POSTGRES_USER: market
      POSTGRES_PASSWORD: password
      POSTGRES_DB: market
    volumes:
      - market_data:/var/lib/postgresql/data

  postgres_giver:
    image: postgres:latest
    environment:
      POSTGRES_USER: giver
      POSTGRES_PASSWORD: password
      POSTGRES_DB: giver
    volumes:
      - giver_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  market_data:
  giver_data:

